### ISSUE TITLE
Support livereload when app crashes

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1118]
When an app has a server side crash we see the web render of the Phoneix app. In the web when the app is updated it triggers a livereload and this will reloads the app state in the browser. We should support this in native as well.
![simulator_screenshot_F834A831-0157-49AF-AE86-92ACA9A542B4](https://github.com/liveview-native/liveview-client-swiftui/assets/18524/006a17e1-6afb-495e-aadf-d28ff95f5775)

**Comment by AZholtkevych** [comment]
That should relate to the Phoenix.Channels. @KronicDeth could we have an issue for that?

**Comment by KronicDeth** [comment]
To be clear `livereload` is the development feature that handles refresh on asset changes @bcardarella. `livereload` is not a feature of `phoenix` and `phoenix.js`, so that wouldn't map to `phoenix-channels-clients`.  `livereload` is part of [`phoenix_live_reload`](https://hex.pm/packages/phoenix_live_reload) and [`phoenix_live_reload.js`] where it uses a [`phoenix:live_reload` channel](https://github.com/phoenixframework/phoenix_live_reload/blob/e8a8d800e63c34fabb217af480b742af78a35872/priv/static/phoenix_live_reload.js#L53) and listens for the [`assets_change`](https://github.com/phoenixframework/phoenix_live_reload/blob/e8a8d800e63c34fabb217af480b742af78a35872/priv/static/phoenix_live_reload.js#L54) event.

If however, you mean that the app reconnects on an error from the backend, that's [reconnect on error and it's in `phoenix-channels-clients`](https://github.com/liveview-native/phoenix-channels-client/pull/18) already, but this issue shouldn't be closed until `liveview-client-swiftui` is using `phoenix-channels-client`.

**Comment by bcardarella** [comment]
@KronicDeth the current behavior on the web is that when you get a server side stack trace it renders in the browser, on code update the app reloads in the browser without a manual reload. We already have livereload supported in the swiftui client. And we support using the WebView to render the stack trace as seen above. What we currently don't have is a way to accept and reload the app if we receive a livereload notification. I assume we'd want some javascript bridge from the webview as the livereload js asset will be running anyway

**Comment by KronicDeth** [comment]
@bcardarella I'd prefer we mirror the JS library separation and make a `phoenix_live_reload` Rust library that depends on `phoenix_channels_client`, but we could also put that in `liveview-native-core`.  I don't see the need to talk to the JS in the webview since Rust can be listening for those events.  The way the JS is handling it is it is likely just replacing the root liveview equivalent to show the code from the server.

**Comment by bcardarella** [comment]
@KronicDeth I agree with a livereload function in core but in this particular case I'd need to check out the implementation of the stack trace rendering. If we're using the webview already that should be running the livereload lib in js and establishing its own websocket connection

**Comment by bcardarella** [comment]
fwiw it would be nice to get a native friendly version of the error page so we can just rely on core

**Comment by KronicDeth** [comment]
@bcardarella 🤔 I suppose the native error page depends on if it is all HTML in which case we need to parse and redo that, but even if it is fairly stable HTML then we can make `~SWIFTUI` version of it and add some check that the error page hasn't changed upstream (like a sha check or something)

**Comment by bcardarella** [comment]
@KronicDeth honestly I'm divided, the pure native view may look better but the current webview is pretty good and less work to support

**Comment by bcardarella** [comment]
This is actually working as I described, I think I had an other issue preventing refresh. Closing
