### ISSUE TITLE
NavigationStack is not keeping the layout components

### ISSUE THREAD

**Issue by cmnstmntmn** [liveview-native/liveview-client-swiftui#1407]
### What happened?

Not sure if this is the intended behaviour, however 
having a menu/NavigationStack as part of `root.swiftui.neex` layout is not rendered when the page is changed.

I'm having two live routes: `home` and `about`.
Each containing a simple `<Text>Page name</Text>`

Both are using `/layouts/root.swiftui.neex` layout template

```heex
<.csrf_token />
<Style url={~p"/assets/app.swiftui.styles"} />

<NavigationStack>
    <%= @inner_content %>

    <Spacer />
   
   
    <HStack>
        <Spacer />
        <.link navigate={~p"/"}><.icon name="house" />Home</.link>
        <Spacer />
        <.link navigate={~p"/about"}><.icon name="person" />About</.link>
        <Spacer />
    </HStack>
</NavigationStack>
```

The problem is that the app menu, is not persisted when navigating from a page to another.

 

https://github.com/user-attachments/assets/2a67db34-6db6-4d65-92a1-d1ad06db8fdc

https://github.com/user-attachments/assets/88c8bfa0-ddca-4b01-a4ee-6469499ad82c

### Library Version

0.3.0-rc.3

### Xcode Version

16.0 beta 3

### Swift Version

6.0

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

18.0

**Comment by bcardarella** [comment]
You may want to check out this (in progress) PR which is going to have guides on how to implement various navigation types

**Comment by bcardarella** [comment]
@cmnstmntmn I forgot to link you to the PR https://github.com/liveview-native/liveview-client-swiftui/pull/1391

**Comment by cmnstmntmn** [comment]
thanks @bcardarella, I'm going to check with that PR

**Comment by carson-katri** [comment]
This is the expected behavior for `NavigationStack`. The content in a NavigationStack is shown only for the root navigation level. When you navigate, the content is replaced with the new route.

There's a couple ways to put content on every page:
1. Move the content into the `app.swiftui.neex` template. This template is used for each route, and should show up when navigating away from the first page.
2. Move the content outside the `NavigationStack` (make it a sibling) in `root.swiftui.neex`. This will ensure it sticks around on each page.

Since you're implementing tabs, I would suggest using a `TabView` to get the native tab experience. As @bcardarella mentioned, we have samples for how to implement that alongside `NavigationStack` coming in #1391, although I'm not sure if the tab demo is in there yet. There's many ways you could hook up the `TabView`, it all depends on how you want your navigation to be structured.

**Comment by cmnstmntmn** [comment]
Thank you @carson-katri, I'll look around.
