### ISSUE TITLE
[RFC] Declarative API for Custom Elements

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-swiftui#250]
Currently, users can declare their own elements via the `CustomRegistry`. However, the API could be more SwiftUI-like and typesafe by using property wrappers for the attributes:

```swift
struct MyCustomElement: View {
  @Attribute("min") private var minimum: Double // crashes if this is not provided with a helpful message
  @Attribute("max") private var maximum: Double?
  @Attribute("measurement") private var measurement // default to `String?`

  @LiveContext<MyRegistry> private var liveContext

  var body: some View {
    MyCustomView(bounds: minimum...(maximum ?? 1), measurement: measurement) {
      liveContext.buildChildren(name: "label", includeDefault: true) // the `LiveContext` wrapper knows about the element, so this is simplified.
    }
  }
}
```

The same View today would be written like this:

```swift
struct MyCustomElement: View {
  @ObservedElement private var element: ElementNode
  let context: LiveContext<MyRegistry>

  var body: some View {
    let minimum = element.attributeValue(for: "min").flatMap(Double.init)!
    let maximum = element.attributeValue(for: "max").flatMap(Double.init)
    MyCustomView(bounds: minimum...(maximum ?? 1), measurement: element.attributeValue(for: "measurement")) {
      context.buildChildren(of: element, withTagName: "label", namespace: "my-custom-element", includeDefaultSlot: true)
    }
  }
}
```

This works well, but doesn't make it immediately obvious from looking at the definition which attributes are available and what their types are. Using property wrappers, the context can be environment-aware and automatically use the correct `ElementNode` when calling its methods.

This would mostly be additive, with the `ObservedElement` wrapper being used in the other wrappers. The live context would need to be passed down through the environment.

Internal element definitions could use this as well.

**Comment by bcardarella** [comment]
I like this idea. But my Swift-fu is pretty weak so I'll let @shadowfacts weigh in

**Comment by shadowfacts** [comment]
I am wholeheartedly in favor of this. The API is already moving in this direction with ObservedElement/FormState/LiveBinding, and I think adding attributes is a natural extension of it.

I'm going to do an initial pass on the context aspect, since the multi-registry changes for #178 mean the context can't be passed through the CustomRegistry methods.

Some API design suggestions for whoever ends up implementing this:
- There should be a new protocol that types that are decodable from attribute values conform to.
- The `wrappedValue` should be used as the fallback, if the attribute isn't provided (non-optional types w/o defaults should still error when missing a value)
- I don't like defaulting the type to `String` or `String?`, I think for variable-type property wrappers you should always specify the type either explicitly or by inference from the wrapped value

**Comment by AZholtkevych** [comment]
According to @carson-katri it has been implemented
