### ISSUE TITLE
EXC_BAD_ACCESS when attempting to access Phoenix server on same network

### ISSUE THREAD

**Issue by supernintendo** [liveview-native/liveview-client-swiftui#806]
Phoenix allows you to bind to 0.0.0.0 which makes your app accessible to other devices on the same network but when I try to do this from my LVN app, it crashes with a EXC_BAD_ACCESS error. I tried to capture a video of this behavior on my iPhone…

https://user-images.githubusercontent.com/5893007/232146533-05c720b3-868e-491a-9ed1-afb43c90c285.mov

![screenshot_2023-04-06_at_9 38 07_pm](https://user-images.githubusercontent.com/5893007/232146573-3c8a097a-ef10-4bcc-bfb1-3e07bbd65881.png)

**Comment by shadowfacts** [comment]
So the underlying issue seems to be that we're hitting the 1MB stack limit on iOS devices (the limit is higher on Macs, which is why it's fine in the Simulator). You run do `reg read sp` in the debugger to read the stack pointer at the point of the exception and compare it to the stack pointer in `start` and observe that the difference is always about a megabyte.

Something about [this switch](https://github.com/liveview-native/liveview-client-swiftui/blob/df8acbd84f880ead4b7dc3f7e97b7e28af58fa92/Sources/LiveViewNative/ViewTree.swift#L25-L50) is causing the stack to grow by about a 450KB—putting us over the limit—between the `fromNodes(_:coordinator:url:)` call and the exception.
